# Generated by Django 5.2.10 on 2026-01-07 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom',
            field=models.CharField(default='Produit inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='nutriscore',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit_de_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='search.produit')),
                ('produit_remplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacement', to='search.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
