# Generated by Django 5.2.10 on 2026-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_produit_categorie_produit_nom_produit_nutriscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
